# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python311:
      python.version: '3.11'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    flake8 .
  displayName: 'Flake8'
  continueOnError: True

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './data/convert_to_parquet.py'
  displayName: 'Convert from csv to parquet'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './features/create.py'
  displayName: 'Create features'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './run.py'
  displayName: 'Run'

- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: './kaggle/submit_to_competition.py'
  displayName: 'Submit to Kaggle'
